# Generated by Django 5.2.17 on 2026-09-01 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='session_key',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=40),
        ),
    ]
