# Generated by Django 5.2.17 on 2026-09-01 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(default='🧺', max_length=10)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Categorías',
                'ordering': ('order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('city', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, max_length=240)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('unit', models.CharField(choices=[('kg', 'kg'), ('unidad', 'unidad'), ('docena', 'docena'), ('paquete', 'paquete'), ('bolsa', 'bolsa')], max_length=20)),
                ('estimated_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('image', models.CharField(default='🧺', help_text='Emoji o referencia visual', max_length=20)),
                ('is_available', models.BooleanField(default=True)),
                ('is_fresh', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalog.market')),
            ],
            options={
                'ordering': ('category__order', 'name'),
            },
        ),
    ]
