# Generated by Django 5.2.17 on 2026-09-01 00:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=12, unique=True)),
                ('guest_name', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('CONFIRMED', 'Pedido confirmado'), ('BUYER_ASSIGNED', 'Comprador asignado'), ('SHOPPING', 'Comprando en el mercado'), ('WAITING_CUSTOMER_APPROVAL', 'Esperando tu aprobación'), ('SHOPPING_COMPLETED', 'Compra terminada'), ('AT_BUFFER', 'Verificando productos'), ('READY_FOR_DELIVERY', 'Listo para entrega'), ('OUT_FOR_DELIVERY', 'En camino'), ('DELIVERED', 'Entregado'), ('CANCELLED', 'Cancelado')], default='CONFIRMED', max_length=40)),
                ('scheduled_date', models.DateField()),
                ('scheduled_window', models.CharField(choices=[('08:00 - 10:00', '08:00 - 10:00'), ('10:00 - 12:00', '10:00 - 12:00'), ('14:00 - 16:00', '14:00 - 16:00'), ('16:00 - 18:00', '16:00 - 18:00')], max_length=30)),
                ('estimated_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('final_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.address')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=7)),
                ('estimated_unit_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('final_unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('preferences', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('FOUND', 'Encontrado'), ('SUBSTITUTED', 'Sustituido'), ('NOT_PURCHASED', 'No comprado')], default='PENDING', max_length=24)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.product')),
            ],
        ),
        migrations.CreateModel(
            name='OrderIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PRICE_CHANGE', 'Cambio de precio'), ('OUT_OF_STOCK', 'Producto agotado'), ('SUBSTITUTION', 'Sustitución')], max_length=24)),
                ('message', models.TextField()),
                ('proposed_product_name', models.CharField(blank=True, max_length=140)),
                ('proposed_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('ACCEPTED', 'Aceptada'), ('REJECTED', 'Rechazada')], default='PENDING', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='orders.orderitem')),
            ],
            options={
                'verbose_name': 'Incidencia',
                'verbose_name_plural': 'Incidencias',
                'ordering': ('-created_at',),
            },
        ),
    ]
