# Generated by Django 5.2.17 on 2026-09-01 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=15, max_digits=8),
        ),
        migrations.AddField(
            model_name='order',
            name='service_fee',
            field=models.DecimalField(decimal_places=2, default=15, max_digits=8),
        ),
    ]
